version: "3"

services:
  postgres:
    image: postgres
    env_file: ./.env
    volumes:
      - /var/lib/postgresql
    ports:
      - "5432:5432"

  golang:
    build: .
    command: ["./wait-for-postgres.sh", "postgres:5432", "--", "go", "run", "server.go"]
    volumes:
      - .:/go/src/github.com/marques999/acme-server
    ports:
      - "${ACME_PORT}:${ACME_PORT}"
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres

  pgadmin:
    image: fenglc/pgadmin4
    volumes:
      - ./pgadmin:/data
    ports:
      - "5050:5050"
    depends_on:
      - postgres