version: "2.1"

services:
  database:
    image: postgres
    volumes:
      - /var/lib/postgresql
    ports: 
      - "5432:5432"
    env_file:
      - ./.env

  pgadmin:
    image: fenglc/pgadmin4
    volumes:
      - ./pgadmin:/data
    ports:
      - "5050:5050"
    links:
      - database:postgres
